module mini_src_cpu #(
    parameter RAM_INIT_FILE = ""
) (
    input  wire        Clock,
    input  wire        Reset,
    input  wire        Stop,
    input  wire [31:0] port_in,

    output wire        Run,
    output wire [4:0]  state_dbg,
    output wire [31:0] BusMuxOut,
    output wire [31:0] PC,
    output wire [31:0] IR,
    output wire [31:0] Y,
    output wire [31:0] MAR,
    output wire [31:0] MDR,
    output wire [31:0] HI,
    output wire [31:0] LO,
    output wire [63:0] Z,
    output wire [31:0] Zhigh,
    output wire [31:0] Zlow,
    output wire [31:0] In_Port,
    output wire [31:0] Out_Port,
    output wire [31:0] MemoryData,
    output wire        CON,
    output wire        addsub_overflow,
    output wire        neg_overflow,
    output wire        mul_overflow,
    output wire        div_by_zero,
    output wire        inc_overflow,
    output wire [31:0] R0,
    output wire [31:0] R1,
    output wire [31:0] R2,
    output wire [31:0] R3,
    output wire [31:0] R4,
    output wire [31:0] R5,
    output wire [31:0] R6,
    output wire [31:0] R7,
    output wire [31:0] R8,
    output wire [31:0] R9,
    output wire [31:0] R10,
    output wire [31:0] R11,
    output wire [31:0] R12,
    output wire [31:0] R13,
    output wire [31:0] R14,
    output wire [31:0] R15
);

    wire Gra, Grb, Grc, Rin, Rout, BAout;
    wire PCin, IRin, Yin, MARin, HIin, LOin, Zin, MDRin, CONin, Out_Portin, R12in_force;
    wire IncPC, Read, Write;
    wire PCout, MDRout, HIout, LOout, Zhighout, Zlowout, In_Portout, Cout;
    wire AND, OR, NOT_op, NEG, SHR, SHRA, SHL, ROR, ROL, ADD, SUB, MUL, DIV;

    control_unit U_CONTROL (
        .Clock(Clock),
        .Reset(Reset),
        .Stop(Stop),
        .IR(IR),
        .CON(CON),
        .Gra(Gra),
        .Grb(Grb),
        .Grc(Grc),
        .Rin(Rin),
        .Rout(Rout),
        .BAout(BAout),
        .PCin(PCin),
        .IRin(IRin),
        .Yin(Yin),
        .MARin(MARin),
        .HIin(HIin),
        .LOin(LOin),
        .Zin(Zin),
        .MDRin(MDRin),
        .CONin(CONin),
        .Out_Portin(Out_Portin),
        .R12in_force(R12in_force),
        .IncPC(IncPC),
        .Read(Read),
        .Write(Write),
        .PCout(PCout),
        .MDRout(MDRout),
        .HIout(HIout),
        .LOout(LOout),
        .Zhighout(Zhighout),
        .Zlowout(Zlowout),
        .In_Portout(In_Portout),
        .Cout(Cout),
        .AND(AND),
        .OR(OR),
        .NOT_op(NOT_op),
        .NEG(NEG),
        .SHR(SHR),
        .SHRA(SHRA),
        .SHL(SHL),
        .ROR(ROR),
        .ROL(ROL),
        .ADD(ADD),
        .SUB(SUB),
        .MUL(MUL),
        .DIV(DIV),
        .Run(Run),
        .state_dbg(state_dbg)
    );

    Datapath_top #(
        .RAM_INIT_FILE(RAM_INIT_FILE)
    ) U_DP_TOP (
        .Clock(Clock),
        .Clear(Reset),
        .Gra(Gra),
        .Grb(Grb),
        .Grc(Grc),
        .Rin(Rin),
        .Rout(Rout),
        .BAout(BAout),
        .PCin(PCin),
        .IRin(IRin),
        .Yin(Yin),
        .MARin(MARin),
        .HIin(HIin),
        .LOin(LOin),
        .Zin(Zin),
        .MDRin(MDRin),
        .CONin(CONin),
        .Out_Portin(Out_Portin),
        .R12in_force(R12in_force),
        .IncPC(IncPC),
        .Read(Read),
        .Write(Write),
        .PCout(PCout),
        .MDRout(MDRout),
        .HIout(HIout),
        .LOout(LOout),
        .Zhighout(Zhighout),
        .Zlowout(Zlowout),
        .In_Portout(In_Portout),
        .Cout(Cout),
        .AND(AND),
        .OR(OR),
        .NOT_op(NOT_op),
        .NEG(NEG),
        .SHR(SHR),
        .SHRA(SHRA),
        .SHL(SHL),
        .ROR(ROR),
        .ROL(ROL),
        .ADD(ADD),
        .SUB(SUB),
        .MUL(MUL),
        .DIV(DIV),
        .port_in(port_in),
        .BusMuxOut(BusMuxOut),
        .PC(PC),
        .IR(IR),
        .Y(Y),
        .MAR(MAR),
        .MDR(MDR),
        .HI(HI),
        .LO(LO),
        .Z(Z),
        .Zhigh(Zhigh),
        .Zlow(Zlow),
        .In_Port(In_Port),
        .Out_Port(Out_Port),
        .MemoryData(MemoryData),
        .CON(CON),
        .addsub_overflow(addsub_overflow),
        .neg_overflow(neg_overflow),
        .mul_overflow(mul_overflow),
        .div_by_zero(div_by_zero),
        .inc_overflow(inc_overflow),
        .R0(R0),
        .R1(R1),
        .R2(R2),
        .R3(R3),
        .R4(R4),
        .R5(R5),
        .R6(R6),
        .R7(R7),
        .R8(R8),
        .R9(R9),
        .R10(R10),
        .R11(R11),
        .R12(R12),
        .R13(R13),
        .R14(R14),
        .R15(R15)
    );

endmodule
