// Lightweight top-level wrapper around Datapath_top for synthesis.
// Only exposes a small set of outputs so the design fits the FPGA I/O limits.
// Use this as the TOP_LEVEL_ENTITY for full compilation; keep Datapath_top for simulation.
module phase_1_synth_top (
    input  wire        Clock,
    input  wire        Clear,
    input  wire [15:0] Rin,
    input  wire        PCin,
    input  wire        IRin,
    input  wire        Yin,
    input  wire        MARin,
    input  wire        HIin,
    input  wire        LOin,
    input  wire        Zin,
    input  wire        IncPC,
    input  wire        MDRin,
    input  wire        Read,
    input  wire [31:0] Mdatain,
    input  wire [15:0] Rout,
    input  wire        PCout,
    input  wire        MDRout,
    input  wire        HIout,
    input  wire        LOout,
    input  wire        Zhighout,
    input  wire        Zlowout,
    input  wire        AND,
    input  wire        OR,
    input  wire        NOT_op,
    input  wire        NEG,
    input  wire        SHR,
    input  wire        SHRA,
    input  wire        SHL,
    input  wire        ROR,
    input  wire        ROL,
    input  wire        ADD,
    input  wire        SUB,
    input  wire        MUL,
    input  wire        DIV,
    output wire [31:0] BusMuxOut,
    output wire [63:0] Z
);
    Datapath_top U_Datapath_top (
        .Clock(Clock),
        .Clear(Clear),
        .Rin(Rin),
        .PCin(PCin),
        .IRin(IRin),
        .Yin(Yin),
        .MARin(MARin),
        .HIin(HIin),
        .LOin(LOin),
        .Zin(Zin),
        .IncPC(IncPC),
        .MDRin(MDRin),
        .Read(Read),
        .Mdatain(Mdatain),
        .Rout(Rout),
        .PCout(PCout),
        .MDRout(MDRout),
        .HIout(HIout),
        .LOout(LOout),
        .Zhighout(Zhighout),
        .Zlowout(Zlowout),
        .AND(AND),
        .OR(OR),
        .NOT_op(NOT_op),
        .NEG(NEG),
        .SHR(SHR),
        .SHRA(SHRA),
        .SHL(SHL),
        .ROR(ROR),
        .ROL(ROL),
        .ADD(ADD),
        .SUB(SUB),
        .MUL(MUL),
        .DIV(DIV),
        .BusMuxOut(BusMuxOut),
        .PC(),
        .IR(),
        .Y(),
        .MAR(),
        .HI(),
        .LO(),
        .Z(Z),
        .Zhigh(),
        .Zlow(),
        .R0(), .R1(), .R2(), .R3(), .R4(), .R5(), .R6(), .R7(),
        .R8(), .R9(), .R10(), .R11(), .R12(), .R13(), .R14(), .R15()
    );
endmodule
