// Synthesis wrapper for the integrated Mini SRC CPU.
// Keep the legacy top-level entity name so the Quartus project does not need
// to be renamed, while exposing a compact debug surface for hardware builds.
module phase_1_synth_top (
    input  wire        Clock,
    input  wire        Clear,
    input  wire        Stop,
    input  wire [31:0] port_in,
    output wire        Run,
    output wire [4:0]  state_dbg,
    output wire [31:0] BusMuxOut,
    output wire [63:0] Z
);
    mini_src_cpu U_CPU (
        .Clock(Clock),
        .Reset(Clear),
        .Stop(Stop),
        .port_in(port_in),
        .Run(Run),
        .state_dbg(state_dbg),
        .BusMuxOut(BusMuxOut),
        .PC(),
        .IR(),
        .Y(),
        .MAR(),
        .MDR(),
        .HI(),
        .LO(),
        .Z(Z),
        .Zhigh(),
        .Zlow(),
        .In_Port(),
        .Out_Port(),
        .MemoryData(),
        .CON(),
        .addsub_overflow(),
        .neg_overflow(),
        .mul_overflow(),
        .div_by_zero(),
        .inc_overflow(),
        .R0(),
        .R1(),
        .R2(),
        .R3(),
        .R4(),
        .R5(),
        .R6(),
        .R7(),
        .R8(),
        .R9(),
        .R10(),
        .R11(),
        .R12(),
        .R13(),
        .R14(),
        .R15()
    );
endmodule
